<p>&nbsp;&nbsp;</p>
<table width="650" border="0" align="center" cellpadding="5" cellspacing="5">
  <tr> 
    <td><div align="left"> <a href="index.jsp"  CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Principal</a> 
         | <a href="gastos.jsp?nMes=<%= new java.util.Date().getMonth() + 1 %>" CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Lan&ccedil;amento de gastos</a>
		 | <a href="despesa.jsp" CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Cadastro de despesas & receitas</a>
		 | <a href="categoria.jsp" CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Cadastro de categorias</a>
		 | <a href="relcategoria.jsp" CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Relat&oacute;rio de categorias</a>
		 | <a href="relexcel.jsp?nMes=<%= new java.util.Date().getMonth() + 1 %>"   CLASS="off" onMouseOver="this.className = 'on';" onMouseOut="this.className = 'off';">Relat&oacute;rio Excel</a> </div></td>
  </tr>
</table>
<p align="center">&nbsp;&nbsp;&nbsp;&nbsp;
  <font color="#000066" size="1" face="Arial, Helvetica, sans-serif"><strong>Copyright 
  2003&copy; Fandrade Web Solutions.</strong></font> 
<h3 align="center"><font color="#000066" size="1" face="Arial, Helvetica, sans-serif">Todos 
  os direitos reservados. All rights reserved.</font></h3>

